name: CI

on:
  pull_request:
    branches:
    - master
    - staging

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run ESLint
      uses: hallee/eslint-action@master
      with:
        files: [src, stories]
