name: CI

on:
  pull_request:
    branches:
    - master
    - staging

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - run: npm install
    - run: npm run lint src/**/* stories/**/*

  testBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm run build-storybook
